/**
 * Enhanced resource preconnection utilities for perfect Core Web Vitals optimization
 * Implements aggressive preconnect, dns-prefetch, preload, and prefetch strategies
 */

export interface PreconnectConfig {
  href: string;
  crossOrigin?: "" | "anonymous" | "use-credentials";
  type?: "preconnect" | "dns-prefetch" | "preload" | "prefetch";
  as?: "font" | "image" | "script" | "style" | "document";
  importance?: "high" | "low";
  fetchpriority?: "high" | "low" | "auto";
  media?: string;
}

/**
 * Critical resource preloads for LCP optimization
 */
export const CRITICAL_PRELOADS: PreconnectConfig[] = [
  // Critical CSS (will be generated by critical CSS extraction)
  {
    href: "/critical.css",
    type: "preload",
    as: "style",
    importance: "high",
    fetchpriority: "high",
  },
  // Hero/LCP images (add specific images here)
  {
    href: "/assets/hero-image.webp",
    type: "preload",
    as: "image",
    importance: "high",
    fetchpriority: "high",
  },
];

/**
 * Critical third-party domains that should be preconnected
 * Ordered by priority - most critical first
 */
export const CRITICAL_PRECONNECTS: PreconnectConfig[] = [
  // Google Fonts - Critical for text rendering (LCP impact)
  {
    href: "https://fonts.googleapis.com",
    type: "preconnect",
    importance: "high",
    fetchpriority: "high",
  },
  {
    href: "https://fonts.gstatic.com",
    type: "preconnect",
    crossOrigin: "",
    importance: "high",
    fetchpriority: "high",
  },

  // Analytics - Important for business metrics but not LCP critical
  {
    href: "https://plausible.io",
    type: "preconnect",
    importance: "low",
  },

  // Calendar scheduling - User experience critical
  {
    href: "https://cal.com",
    type: "preconnect",
    crossOrigin: "",
    importance: "high",
  },

  // Vercel Analytics and Speed Insights
  {
    href: "https://vitals.vercel-insights.com",
    type: "preconnect",
    importance: "high",
  },

  // CDN resources (if using external CDNs)
  {
    href: "https://cdn.jsdelivr.net",
    type: "dns-prefetch",
    importance: "low",
  },
];

/**
 * Route-based prefetch configurations for Dutch navigation patterns
 * Based on typical user journeys
 */
export const ROUTE_PREFETCH_CONFIG: Record<string, PreconnectConfig[]> = {
  "/": [
    // From homepage, users typically go to services or contact
    { href: "/diensten", type: "prefetch", as: "document", importance: "high" },
    { href: "/contact", type: "prefetch", as: "document", importance: "high" },
    { href: "/werkwijze", type: "prefetch", as: "document", importance: "low" },
  ],
  "/diensten": [
    // From services, users typically want to contact or see process
    { href: "/contact", type: "prefetch", as: "document", importance: "high" },
    {
      href: "/werkwijze",
      type: "prefetch",
      as: "document",
      importance: "high",
    },
    { href: "/", type: "prefetch", as: "document", importance: "low" },
  ],
  "/werkwijze": [
    // From process page, users typically go to contact
    { href: "/contact", type: "prefetch", as: "document", importance: "high" },
    { href: "/diensten", type: "prefetch", as: "document", importance: "low" },
  ],
  "/contact": [
    // Contact is usually end of funnel, light prefetching
    { href: "/diensten", type: "prefetch", as: "document", importance: "low" },
  ],
};

/**
 * DNS prefetch configurations for non-critical domains
 * Used for resources that may be needed later
 */
export const DNS_PREFETCH_DOMAINS = [
  "https://www.google-analytics.com",
  "https://www.googletagmanager.com",
  "https://apis.google.com",
  "https://youtube.com",
  "https://vimeo.com",
] as const;

/**
 * Page-specific resource preloading configurations
 */
export const PAGE_SPECIFIC_PRECONNECTS = {
  "/contact": [
    {
      href: "https://cal.com",
      type: "preconnect" as const,
      crossOrigin: "" as const,
      importance: "high" as const,
    },
  ],
  "/": [
    {
      href: "https://plausible.io",
      type: "preconnect" as const,
      importance: "high" as const,
    },
  ],
} as const;

/**
 * Generate all preconnect/dns-prefetch links for a specific page
 */
export function generateResourcePreconnects(
  pathname?: string,
): PreconnectConfig[] {
  const preconnects = [...CRITICAL_PRECONNECTS];

  // Add DNS prefetch for non-critical domains
  const dnsPrefetches = DNS_PREFETCH_DOMAINS.map((domain) => ({
    href: domain,
    type: "dns-prefetch" as const,
    importance: "low" as const,
  }));

  preconnects.push(...dnsPrefetches);

  // Add page-specific preconnects
  if (
    pathname &&
    PAGE_SPECIFIC_PRECONNECTS[
      pathname as keyof typeof PAGE_SPECIFIC_PRECONNECTS
    ]
  ) {
    const pageSpecific =
      PAGE_SPECIFIC_PRECONNECTS[
        pathname as keyof typeof PAGE_SPECIFIC_PRECONNECTS
      ];
    preconnects.push(...pageSpecific);
  }

  return preconnects;
}

/**
 * Generate resource hints based on connection quality
 */
export function getAdaptiveResourceHints() {
  if (typeof window === "undefined") return CRITICAL_PRECONNECTS;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const connection = (navigator as any).connection;
  if (connection) {
    const { effectiveType, saveData } = connection;

    // Reduce preconnects for slow connections or data saver mode
    if (saveData || effectiveType === "slow-2g" || effectiveType === "2g") {
      return CRITICAL_PRECONNECTS.filter(
        (config) => config.importance === "high",
      );
    }
  }

  return CRITICAL_PRECONNECTS;
}

/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Advanced preconnect and resource hints optimization
 * Optimized for Dutch CDNs and hosting providers
 */
export const RESOURCE_STRATEGIES = {
  // Fonts should be preconnected and preloaded
  fonts: {
    strategy: "preconnect-preload",
    priority: "high",
    timing: "immediate",
  },

  // Analytics can be preconnected but loaded later
  analytics: {
    strategy: "preconnect-defer",
    priority: "high",
    timing: "after-load",
  },

  // Social/external widgets should be lazy loaded
  social: {
    strategy: "dns-prefetch-lazy",
    priority: "low",
    timing: "on-interaction",
  },

  // API endpoints should be preconnected for forms
  api: {
    strategy: "preconnect",
    priority: "high",
    timing: "on-page-load",
  },
} as const;

/**
 * Monitor and optimize resource loading performance
 */
export function trackResourcePerformance() {
  if (typeof window === "undefined") return;

  // Track resource loading times
  const observer = new PerformanceObserver((list) => {
    for (const entry of list.getEntries()) {
      if (entry.entryType === "resource") {
        const resourceEntry = entry as PerformanceResourceTiming;

        // Log slow third-party resources
        if (resourceEntry.duration > 1000) {
          console.warn(
            `Slow resource detected: ${resourceEntry.name} took ${resourceEntry.duration}ms`,
          );
        }
      }
    }
  });

  observer.observe({ entryTypes: ["resource"] });
}

export default generateResourcePreconnects;
