/**
 * Comprehensive monitoring types for SEO, Performance, and Health tracking
 */

// Core Web Vitals monitoring
export interface CoreWebVitalsMetrics {
  fcp: number; // First Contentful Paint
  lcp: number; // Largest Contentful Paint
  fid: number; // First Input Delay
  cls: number; // Cumulative Layout Shift
  ttfb: number; // Time to First Byte
  timestamp: number;
  url: string;
  userAgent: string;
  connectionType?: string;
}

export interface PerformanceAlert {
  metric: keyof CoreWebVitalsMetrics;
  threshold: number;
  currentValue: number;
  severity: 'low' | 'medium' | 'high' | 'critical';
  timestamp: number;
  url: string;
}

// SEO Health monitoring
export interface SEOHealthCheck {
  url: string;
  timestamp: number;
  status: 'healthy' | 'warning' | 'critical';
  checks: {
    metaTags: SEOMetaTagsCheck;
    structuredData: StructuredDataCheck;
    performance: PerformanceCheck;
    indexability: IndexabilityCheck;
    canonicalization: CanonicalizationCheck;
    socialSharing: SocialSharingCheck;
  };
  score: number; // 0-100
  issues: SEOIssue[];
}

export interface SEOMetaTagsCheck {
  title: boolean;
  description: boolean;
  keywords: boolean;
  robots: boolean;
  canonical: boolean;
  hreflang: boolean;
  openGraph: boolean;
  twitterCard: boolean;
}

export interface StructuredDataCheck {
  present: boolean;
  valid: boolean;
  types: string[];
  errors: string[];
  warnings: string[];
  richSnippetsEligible: boolean;
}

export interface PerformanceCheck {
  coreWebVitals: {
    lcp: { value: number; status: 'good' | 'needs-improvement' | 'poor' };
    fid: { value: number; status: 'good' | 'needs-improvement' | 'poor' };
    cls: { value: number; status: 'good' | 'needs-improvement' | 'poor' };
  };
  lighthouse: {
    performance: number;
    accessibility: number;
    bestPractices: number;
    seo: number;
  };
}

export interface IndexabilityCheck {
  robotsAllowed: boolean;
  noindexPresent: boolean;
  canonicalCorrect: boolean;
  xmlSitemapPresent: boolean;
  internalLinksCount: number;
  httpStatus: number;
}

export interface CanonicalizationCheck {
  hasCanonical: boolean;
  canonicalUrl: string;
  isCanonicalCorrect: boolean;
  duplicateContent: boolean;
}

export interface SocialSharingCheck {
  openGraph: {
    title: boolean;
    description: boolean;
    image: boolean;
    url: boolean;
    type: boolean;
  };
  twitter: {
    card: boolean;
    title: boolean;
    description: boolean;
    image: boolean;
  };
}

export interface SEOIssue {
  type: 'error' | 'warning' | 'info';
  category: 'meta' | 'content' | 'technical' | 'performance' | 'accessibility';
  message: string;
  impact: 'high' | 'medium' | 'low';
  recommendation: string;
  url?: string;
}

// 404 and redirect monitoring
export interface NotFoundMonitoring {
  url: string;
  timestamp: number;
  referer?: string;
  userAgent: string;
  ipAddress: string;
  frequency: number;
  suggestedRedirect?: string;
  isFixed: boolean;
}

export interface SmartRedirect {
  from: string;
  to: string;
  type: 301 | 302 | 307 | 308;
  reason: 'moved' | 'renamed' | 'consolidated' | 'similar-content';
  confidence: number; // 0-1
  autoGenerated: boolean;
  timestamp: number;
}

// Search query tracking
export interface SearchQueryData {
  query: string;
  impressions: number;
  clicks: number;
  ctr: number; // Click-through rate
  averagePosition: number;
  timestamp: number;
  device: 'desktop' | 'mobile' | 'tablet';
  country: string;
  page: string;
}

export interface SearchConsoleMetrics {
  totalClicks: number;
  totalImpressions: number;
  averageCTR: number;
  averagePosition: number;
  topQueries: SearchQueryData[];
  topPages: string[];
  deviceBreakdown: Record<string, number>;
  countryBreakdown: Record<string, number>;
  dateRange: {
    start: string;
    end: string;
  };
}

// Competitor analysis
export interface CompetitorKeywordGap {
  keyword: string;
  competitorUrl: string;
  competitorPosition: number;
  ourPosition?: number;
  searchVolume: number;
  difficulty: number;
  opportunity: 'high' | 'medium' | 'low';
  intent: 'informational' | 'navigational' | 'commercial' | 'transactional';
  gap: 'missing' | 'ranking-lower' | 'opportunity';
}

export interface CompetitorAnalysis {
  competitor: string;
  domain: string;
  timestamp: number;
  keywordGaps: CompetitorKeywordGap[];
  contentGaps: ContentGap[];
  backlinksComparison: BacklinksComparison;
  technicalGaps: TechnicalGap[];
}

export interface ContentGap {
  topic: string;
  competitorPages: string[];
  ourCoverage: 'none' | 'partial' | 'full';
  opportunity: 'high' | 'medium' | 'low';
  recommendedAction: string;
}

export interface BacklinksComparison {
  competitorBacklinks: number;
  ourBacklinks: number;
  gap: number;
  opportunityDomains: string[];
}

export interface TechnicalGap {
  area: string;
  competitorImplementation: string;
  ourImplementation: string;
  recommendation: string;
  priority: 'high' | 'medium' | 'low';
}

// XML Sitemap validation
export interface SitemapValidation {
  url: string;
  timestamp: number;
  isValid: boolean;
  urlCount: number;
  issues: SitemapIssue[];
  lastModified?: string;
  indexSubmissionStatus: 'submitted' | 'pending' | 'indexed' | 'error';
  coverageReport: {
    submitted: number;
    indexed: number;
    errors: number;
    warnings: number;
  };
}

export interface SitemapIssue {
  type: 'error' | 'warning';
  url?: string;
  message: string;
  recommendation: string;
}

// Alert system
export interface MonitoringAlert {
  id: string;
  type: 'performance' | 'seo' | '404' | 'sitemap' | 'indexing' | 'security';
  severity: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  message: string;
  url?: string;
  timestamp: number;
  acknowledged: boolean;
  resolved: boolean;
  metadata: Record<string, any>;
}

export interface AlertConfig {
  enabled: boolean;
  thresholds: {
    performance: {
      lcp: number;
      fid: number;
      cls: number;
    };
    seo: {
      minScore: number;
      maxIssues: number;
    };
    notFound: {
      maxDaily: number;
      frequencyThreshold: number;
    };
  };
  notifications: {
    email: boolean;
    webhook?: string;
    slack?: string;
  };
  schedule: {
    dailyCheck: boolean;
    weeklyReport: boolean;
    monthlyAnalysis: boolean;
  };
}

// Dashboard data
export interface MonitoringDashboard {
  timestamp: number;
  overview: {
    seoScore: number;
    performanceScore: number;
    issuesCount: number;
    alertsCount: number;
  };
  recentAlerts: MonitoringAlert[];
  coreWebVitals: CoreWebVitalsMetrics;
  seoHealth: SEOHealthCheck;
  searchQueries: SearchQueryData[];
  topIssues: SEOIssue[];
  competitorInsights: CompetitorKeywordGap[];
}

// API responses
export interface MonitoringAPIResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  timestamp: number;
}

export type MonitoringEndpoint = 
  | '/api/monitoring/core-web-vitals'
  | '/api/monitoring/seo-health'
  | '/api/monitoring/404s'
  | '/api/monitoring/search-queries'
  | '/api/monitoring/competitors'
  | '/api/monitoring/sitemap'
  | '/api/monitoring/alerts'
  | '/api/monitoring/dashboard';