export interface DutchCity {
  name: string;
  slug: string;
  province: string;
  postalCodes: string[];
  coordinates: {
    lat: number;
    lng: number;
  };
  population: number;
  keywords: {
    primary: string[];
    secondary: string[];
    longTail: string[];
  };
  localInfo: {
    chamberOfCommerce?: string;
    municipality: string;
    region: string;
    dialCode: string;
  };
  businessHours?: {
    monday: string;
    tuesday: string;
    wednesday: string;
    thursday: string;
    friday: string;
    saturday?: string;
    sunday?: string;
  };
}

export interface LocalBusinessData {
  name: string;
  legalName: string;
  address: {
    streetAddress: string;
    addressLocality: string;
    postalCode: string;
    addressRegion: string;
    addressCountry: string;
  };
  phone: string;
  email: string;
  url: string;
  kvkNumber: string; // Dutch Chamber of Commerce number
  vatNumber: string; // BTW number
  businessHours: {
    monday: string;
    tuesday: string;
    wednesday: string;
    thursday: string;
    friday: string;
    saturday?: string;
    sunday?: string;
  };
  holidays: {
    name: string;
    date: string;
    closed: boolean;
  }[];
  serviceAreas: string[];
  categories: string[];
}

// Top 25 Dutch cities by population and business potential
export const dutchCities: DutchCity[] = [
  {
    name: "Amsterdam",
    slug: "amsterdam",
    province: "Noord-Holland",
    postalCodes: [
      "1000",
      "1001",
      "1002",
      "1003",
      "1004",
      "1005",
      "1006",
      "1007",
      "1008",
      "1009",
      "1010",
      "1011",
      "1012",
      "1013",
      "1014",
      "1015",
      "1016",
      "1017",
      "1018",
      "1019",
    ],
    coordinates: { lat: 52.3676, lng: 4.9041 },
    population: 873338,
    keywords: {
      primary: [
        "website laten maken amsterdam",
        "webdesign amsterdam",
        "webontwikkeling amsterdam",
      ],
      secondary: [
        "wordpress amsterdam",
        "e-commerce website amsterdam",
        "seo specialist amsterdam",
      ],
      longTail: [
        "professionele website laten maken amsterdam",
        "responsive webdesign amsterdam",
        "webshop laten bouwen amsterdam",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Amsterdam",
      municipality: "Amsterdam",
      region: "Metropoolregio Amsterdam",
      dialCode: "020",
    },
  },
  {
    name: "Rotterdam",
    slug: "rotterdam",
    province: "Zuid-Holland",
    postalCodes: [
      "3000",
      "3001",
      "3002",
      "3003",
      "3004",
      "3005",
      "3006",
      "3007",
      "3008",
      "3009",
      "3010",
      "3011",
      "3012",
      "3013",
      "3014",
      "3015",
      "3016",
      "3017",
      "3018",
      "3019",
    ],
    coordinates: { lat: 51.9244, lng: 4.4777 },
    population: 651446,
    keywords: {
      primary: [
        "website laten maken rotterdam",
        "webdesign rotterdam",
        "webontwikkeling rotterdam",
      ],
      secondary: [
        "wordpress rotterdam",
        "e-commerce website rotterdam",
        "seo specialist rotterdam",
      ],
      longTail: [
        "professionele website laten maken rotterdam",
        "responsive webdesign rotterdam",
        "webshop laten bouwen rotterdam",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Rotterdam",
      municipality: "Rotterdam",
      region: "Metropoolregio Rotterdam Den Haag",
      dialCode: "010",
    },
  },
  {
    name: "Den Haag",
    slug: "den-haag",
    province: "Zuid-Holland",
    postalCodes: [
      "2490",
      "2491",
      "2492",
      "2493",
      "2494",
      "2495",
      "2496",
      "2497",
      "2498",
      "2499",
      "2500",
      "2501",
      "2502",
      "2503",
      "2504",
      "2505",
      "2506",
      "2507",
      "2508",
      "2509",
    ],
    coordinates: { lat: 52.0705, lng: 4.3007 },
    population: 547757,
    keywords: {
      primary: [
        "website laten maken den haag",
        "webdesign den haag",
        "webontwikkeling den haag",
      ],
      secondary: [
        "wordpress den haag",
        "e-commerce website den haag",
        "seo specialist den haag",
      ],
      longTail: [
        "professionele website laten maken den haag",
        "responsive webdesign den haag",
        "webshop laten bouwen den haag",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Den Haag",
      municipality: "Den Haag",
      region: "Metropoolregio Rotterdam Den Haag",
      dialCode: "070",
    },
  },
  {
    name: "Utrecht",
    slug: "utrecht",
    province: "Utrecht",
    postalCodes: [
      "3500",
      "3501",
      "3502",
      "3503",
      "3504",
      "3505",
      "3506",
      "3507",
      "3508",
      "3509",
      "3510",
      "3511",
      "3512",
      "3513",
      "3514",
      "3515",
      "3516",
      "3517",
      "3518",
      "3519",
    ],
    coordinates: { lat: 52.0907, lng: 5.1214 },
    population: 361699,
    keywords: {
      primary: [
        "website laten maken utrecht",
        "webdesign utrecht",
        "webontwikkeling utrecht",
      ],
      secondary: [
        "wordpress utrecht",
        "e-commerce website utrecht",
        "seo specialist utrecht",
      ],
      longTail: [
        "professionele website laten maken utrecht",
        "responsive webdesign utrecht",
        "webshop laten bouwen utrecht",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Utrecht",
      municipality: "Utrecht",
      region: "Stadsregio Utrecht",
      dialCode: "030",
    },
  },
  {
    name: "Eindhoven",
    slug: "eindhoven",
    province: "Noord-Brabant",
    postalCodes: [
      "5600",
      "5601",
      "5602",
      "5603",
      "5604",
      "5605",
      "5606",
      "5607",
      "5608",
      "5609",
      "5610",
      "5611",
      "5612",
      "5613",
      "5614",
      "5615",
      "5616",
      "5617",
      "5618",
      "5619",
    ],
    coordinates: { lat: 51.4416, lng: 5.4697 },
    population: 238326,
    keywords: {
      primary: [
        "website laten maken eindhoven",
        "webdesign eindhoven",
        "webontwikkeling eindhoven",
      ],
      secondary: [
        "wordpress eindhoven",
        "e-commerce website eindhoven",
        "seo specialist eindhoven",
      ],
      longTail: [
        "professionele website laten maken eindhoven",
        "responsive webdesign eindhoven",
        "webshop laten bouwen eindhoven",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Eindhoven",
      municipality: "Eindhoven",
      region: "Metropoolregio Eindhoven",
      dialCode: "040",
    },
  },
  {
    name: "Groningen",
    slug: "groningen",
    province: "Groningen",
    postalCodes: [
      "9700",
      "9701",
      "9702",
      "9703",
      "9704",
      "9705",
      "9706",
      "9707",
      "9708",
      "9709",
      "9710",
      "9711",
      "9712",
      "9713",
      "9714",
      "9715",
      "9716",
      "9717",
      "9718",
      "9719",
    ],
    coordinates: { lat: 53.2194, lng: 6.5665 },
    population: 235287,
    keywords: {
      primary: [
        "website laten maken groningen",
        "webdesign groningen",
        "webontwikkeling groningen",
      ],
      secondary: [
        "wordpress groningen",
        "e-commerce website groningen",
        "seo specialist groningen",
      ],
      longTail: [
        "professionele website laten maken groningen",
        "responsive webdesign groningen",
        "webshop laten bouwen groningen",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Groningen",
      municipality: "Groningen",
      region: "Groningen-Assen",
      dialCode: "050",
    },
  },
  {
    name: "Tilburg",
    slug: "tilburg",
    province: "Noord-Brabant",
    postalCodes: [
      "5000",
      "5001",
      "5002",
      "5003",
      "5004",
      "5005",
      "5006",
      "5007",
      "5008",
      "5009",
      "5010",
      "5011",
      "5012",
      "5013",
      "5014",
      "5015",
      "5016",
      "5017",
      "5018",
      "5019",
    ],
    coordinates: { lat: 51.5555, lng: 5.0913 },
    population: 222601,
    keywords: {
      primary: [
        "website laten maken tilburg",
        "webdesign tilburg",
        "webontwikkeling tilburg",
      ],
      secondary: [
        "wordpress tilburg",
        "e-commerce website tilburg",
        "seo specialist tilburg",
      ],
      longTail: [
        "professionele website laten maken tilburg",
        "responsive webdesign tilburg",
        "webshop laten bouwen tilburg",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Tilburg",
      municipality: "Tilburg",
      region: "West-Brabant",
      dialCode: "013",
    },
  },
  {
    name: "Almere",
    slug: "almere",
    province: "Flevoland",
    postalCodes: [
      "1300",
      "1301",
      "1302",
      "1303",
      "1304",
      "1305",
      "1306",
      "1307",
      "1308",
      "1309",
      "1310",
      "1311",
      "1312",
      "1313",
      "1314",
      "1315",
      "1316",
      "1317",
      "1318",
      "1319",
    ],
    coordinates: { lat: 52.3508, lng: 5.2647 },
    population: 218096,
    keywords: {
      primary: [
        "website laten maken almere",
        "webdesign almere",
        "webontwikkeling almere",
      ],
      secondary: [
        "wordpress almere",
        "e-commerce website almere",
        "seo specialist almere",
      ],
      longTail: [
        "professionele website laten maken almere",
        "responsive webdesign almere",
        "webshop laten bouwen almere",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Almere",
      municipality: "Almere",
      region: "Flevoland",
      dialCode: "036",
    },
  },
  {
    name: "Breda",
    slug: "breda",
    province: "Noord-Brabant",
    postalCodes: [
      "4800",
      "4801",
      "4802",
      "4803",
      "4804",
      "4805",
      "4806",
      "4807",
      "4808",
      "4809",
      "4810",
      "4811",
      "4812",
      "4813",
      "4814",
      "4815",
      "4816",
      "4817",
      "4818",
      "4819",
    ],
    coordinates: { lat: 51.5719, lng: 4.7683 },
    population: 184271,
    keywords: {
      primary: [
        "website laten maken breda",
        "webdesign breda",
        "webontwikkeling breda",
      ],
      secondary: [
        "wordpress breda",
        "e-commerce website breda",
        "seo specialist breda",
      ],
      longTail: [
        "professionele website laten maken breda",
        "responsive webdesign breda",
        "webshop laten bouwen breda",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Breda",
      municipality: "Breda",
      region: "West-Brabant",
      dialCode: "076",
    },
  },
  {
    name: "Nijmegen",
    slug: "nijmegen",
    province: "Gelderland",
    postalCodes: [
      "6500",
      "6501",
      "6502",
      "6503",
      "6504",
      "6505",
      "6506",
      "6507",
      "6508",
      "6509",
      "6510",
      "6511",
      "6512",
      "6513",
      "6514",
      "6515",
      "6516",
      "6517",
      "6518",
      "6519",
    ],
    coordinates: { lat: 51.8426, lng: 5.8518 },
    population: 179073,
    keywords: {
      primary: [
        "website laten maken nijmegen",
        "webdesign nijmegen",
        "webontwikkeling nijmegen",
      ],
      secondary: [
        "wordpress nijmegen",
        "e-commerce website nijmegen",
        "seo specialist nijmegen",
      ],
      longTail: [
        "professionele website laten maken nijmegen",
        "responsive webdesign nijmegen",
        "webshop laten bouwen nijmegen",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Nijmegen",
      municipality: "Nijmegen",
      region: "Arnhem-Nijmegen",
      dialCode: "024",
    },
  },
  {
    name: "Haarlem",
    slug: "haarlem",
    province: "Noord-Holland",
    postalCodes: [
      "2000",
      "2001",
      "2002",
      "2003",
      "2004",
      "2005",
      "2006",
      "2007",
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
    ],
    coordinates: { lat: 52.3874, lng: 4.6462 },
    population: 162961,
    keywords: {
      primary: [
        "website laten maken haarlem",
        "webdesign haarlem",
        "webontwikkeling haarlem",
      ],
      secondary: [
        "wordpress haarlem",
        "e-commerce website haarlem",
        "seo specialist haarlem",
      ],
      longTail: [
        "professionele website laten maken haarlem",
        "responsive webdesign haarlem",
        "webshop laten bouwen haarlem",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Haarlem",
      municipality: "Haarlem",
      region: "Metropoolregio Amsterdam",
      dialCode: "023",
    },
  },
  {
    name: "Arnhem",
    slug: "arnhem",
    province: "Gelderland",
    postalCodes: [
      "6800",
      "6801",
      "6802",
      "6803",
      "6804",
      "6805",
      "6806",
      "6807",
      "6808",
      "6809",
      "6810",
      "6811",
      "6812",
      "6813",
      "6814",
      "6815",
      "6816",
      "6817",
      "6818",
      "6819",
    ],
    coordinates: { lat: 51.9851, lng: 5.8987 },
    population: 161368,
    keywords: {
      primary: [
        "website laten maken arnhem",
        "webdesign arnhem",
        "webontwikkeling arnhem",
      ],
      secondary: [
        "wordpress arnhem",
        "e-commerce website arnhem",
        "seo specialist arnhem",
      ],
      longTail: [
        "professionele website laten maken arnhem",
        "responsive webdesign arnhem",
        "webshop laten bouwen arnhem",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Arnhem",
      municipality: "Arnhem",
      region: "Arnhem-Nijmegen",
      dialCode: "026",
    },
  },
  {
    name: "Zaanstad",
    slug: "zaanstad",
    province: "Noord-Holland",
    postalCodes: [
      "1500",
      "1501",
      "1502",
      "1503",
      "1504",
      "1505",
      "1506",
      "1507",
      "1508",
      "1509",
      "1510",
      "1511",
      "1512",
      "1513",
      "1514",
      "1515",
      "1516",
      "1517",
      "1518",
      "1519",
    ],
    coordinates: { lat: 52.4389, lng: 4.8267 },
    population: 156711,
    keywords: {
      primary: [
        "website laten maken zaanstad",
        "webdesign zaanstad",
        "webontwikkeling zaanstad",
      ],
      secondary: [
        "wordpress zaanstad",
        "e-commerce website zaanstad",
        "seo specialist zaanstad",
      ],
      longTail: [
        "professionele website laten maken zaanstad",
        "responsive webdesign zaanstad",
        "webshop laten bouwen zaanstad",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Zaanstad",
      municipality: "Zaanstad",
      region: "Metropoolregio Amsterdam",
      dialCode: "075",
    },
  },
  {
    name: "Apeldoorn",
    slug: "apeldoorn",
    province: "Gelderland",
    postalCodes: [
      "7300",
      "7301",
      "7302",
      "7303",
      "7304",
      "7305",
      "7306",
      "7307",
      "7308",
      "7309",
      "7310",
      "7311",
      "7312",
      "7313",
      "7314",
      "7315",
      "7316",
      "7317",
      "7318",
      "7319",
    ],
    coordinates: { lat: 52.2112, lng: 5.9699 },
    population: 165525,
    keywords: {
      primary: [
        "website laten maken apeldoorn",
        "webdesign apeldoorn",
        "webontwikkeling apeldoorn",
      ],
      secondary: [
        "wordpress apeldoorn",
        "e-commerce website apeldoorn",
        "seo specialist apeldoorn",
      ],
      longTail: [
        "professionele website laten maken apeldoorn",
        "responsive webdesign apeldoorn",
        "webshop laten bouwen apeldoorn",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Apeldoorn",
      municipality: "Apeldoorn",
      region: "Stedendriehoek",
      dialCode: "055",
    },
  },
  {
    name: "Enschede",
    slug: "enschede",
    province: "Overijssel",
    postalCodes: [
      "7500",
      "7501",
      "7502",
      "7503",
      "7504",
      "7505",
      "7506",
      "7507",
      "7508",
      "7509",
      "7510",
      "7511",
      "7512",
      "7513",
      "7514",
      "7515",
      "7516",
      "7517",
      "7518",
      "7519",
    ],
    coordinates: { lat: 52.2215, lng: 6.8937 },
    population: 159734,
    keywords: {
      primary: [
        "website laten maken enschede",
        "webdesign enschede",
        "webontwikkeling enschede",
      ],
      secondary: [
        "wordpress enschede",
        "e-commerce website enschede",
        "seo specialist enschede",
      ],
      longTail: [
        "professionele website laten maken enschede",
        "responsive webdesign enschede",
        "webshop laten bouwen enschede",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Enschede",
      municipality: "Enschede",
      region: "Twente",
      dialCode: "053",
    },
  },
  {
    name: "Haarlemmermeer",
    slug: "haarlemmermeer",
    province: "Noord-Holland",
    postalCodes: [
      "2130",
      "2131",
      "2132",
      "2133",
      "2134",
      "2135",
      "2136",
      "2137",
      "2138",
      "2139",
      "2140",
      "2141",
      "2142",
      "2143",
      "2144",
      "2145",
      "2146",
      "2147",
      "2148",
      "2149",
    ],
    coordinates: { lat: 52.3007, lng: 4.69 },
    population: 156039,
    keywords: {
      primary: [
        "website laten maken haarlemmermeer",
        "webdesign haarlemmermeer",
        "webontwikkeling haarlemmermeer",
      ],
      secondary: [
        "wordpress haarlemmermeer",
        "e-commerce website haarlemmermeer",
        "seo specialist haarlemmermeer",
      ],
      longTail: [
        "professionele website laten maken haarlemmermeer",
        "responsive webdesign haarlemmermeer",
        "webshop laten bouwen haarlemmermeer",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Haarlemmermeer",
      municipality: "Haarlemmermeer",
      region: "Metropoolregio Amsterdam",
      dialCode: "023",
    },
  },
  {
    name: "Amersfoort",
    slug: "amersfoort",
    province: "Utrecht",
    postalCodes: [
      "3800",
      "3801",
      "3802",
      "3803",
      "3804",
      "3805",
      "3806",
      "3807",
      "3808",
      "3809",
      "3810",
      "3811",
      "3812",
      "3813",
      "3814",
      "3815",
      "3816",
      "3817",
      "3818",
      "3819",
    ],
    coordinates: { lat: 52.1561, lng: 5.3878 },
    population: 157279,
    keywords: {
      primary: [
        "website laten maken amersfoort",
        "webdesign amersfoort",
        "webontwikkeling amersfoort",
      ],
      secondary: [
        "wordpress amersfoort",
        "e-commerce website amersfoort",
        "seo specialist amersfoort",
      ],
      longTail: [
        "professionele website laten maken amersfoort",
        "responsive webdesign amersfoort",
        "webshop laten bouwen amersfoort",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Amersfoort",
      municipality: "Amersfoort",
      region: "Stadsregio Utrecht",
      dialCode: "033",
    },
  },
  {
    name: "Dordrecht",
    slug: "dordrecht",
    province: "Zuid-Holland",
    postalCodes: [
      "3300",
      "3301",
      "3302",
      "3303",
      "3304",
      "3305",
      "3306",
      "3307",
      "3308",
      "3309",
      "3310",
      "3311",
      "3312",
      "3313",
      "3314",
      "3315",
      "3316",
      "3317",
      "3318",
      "3319",
    ],
    coordinates: { lat: 51.8133, lng: 4.6901 },
    population: 119200,
    keywords: {
      primary: [
        "website laten maken dordrecht",
        "webdesign dordrecht",
        "webontwikkeling dordrecht",
      ],
      secondary: [
        "wordpress dordrecht",
        "e-commerce website dordrecht",
        "seo specialist dordrecht",
      ],
      longTail: [
        "professionele website laten maken dordrecht",
        "responsive webdesign dordrecht",
        "webshop laten bouwen dordrecht",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Dordrecht",
      municipality: "Dordrecht",
      region: "Zuid-Holland Zuid",
      dialCode: "078",
    },
  },
  {
    name: "Leiden",
    slug: "leiden",
    province: "Zuid-Holland",
    postalCodes: [
      "2300",
      "2301",
      "2302",
      "2303",
      "2304",
      "2305",
      "2306",
      "2307",
      "2308",
      "2309",
      "2310",
      "2311",
      "2312",
      "2313",
      "2314",
      "2315",
      "2316",
      "2317",
      "2318",
      "2319",
    ],
    coordinates: { lat: 52.1601, lng: 4.497 },
    population: 125174,
    keywords: {
      primary: [
        "website laten maken leiden",
        "webdesign leiden",
        "webontwikkeling leiden",
      ],
      secondary: [
        "wordpress leiden",
        "e-commerce website leiden",
        "seo specialist leiden",
      ],
      longTail: [
        "professionele website laten maken leiden",
        "responsive webdesign leiden",
        "webshop laten bouwen leiden",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Leiden",
      municipality: "Leiden",
      region: "Holland Rijnland",
      dialCode: "071",
    },
  },
  {
    name: "Zoetermeer",
    slug: "zoetermeer",
    province: "Zuid-Holland",
    postalCodes: [
      "2700",
      "2701",
      "2702",
      "2703",
      "2704",
      "2705",
      "2706",
      "2707",
      "2708",
      "2709",
      "2710",
      "2711",
      "2712",
      "2713",
      "2714",
      "2715",
      "2716",
      "2717",
      "2718",
      "2719",
    ],
    coordinates: { lat: 52.0575, lng: 4.4937 },
    population: 125283,
    keywords: {
      primary: [
        "website laten maken zoetermeer",
        "webdesign zoetermeer",
        "webontwikkeling zoetermeer",
      ],
      secondary: [
        "wordpress zoetermeer",
        "e-commerce website zoetermeer",
        "seo specialist zoetermeer",
      ],
      longTail: [
        "professionele website laten maken zoetermeer",
        "responsive webdesign zoetermeer",
        "webshop laten bouwen zoetermeer",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Zoetermeer",
      municipality: "Zoetermeer",
      region: "Metropoolregio Rotterdam Den Haag",
      dialCode: "079",
    },
  },
  {
    name: "Zwolle",
    slug: "zwolle",
    province: "Overijssel",
    postalCodes: [
      "8000",
      "8001",
      "8002",
      "8003",
      "8004",
      "8005",
      "8006",
      "8007",
      "8008",
      "8009",
      "8010",
      "8011",
      "8012",
      "8013",
      "8014",
      "8015",
      "8016",
      "8017",
      "8018",
      "8019",
    ],
    coordinates: { lat: 52.5168, lng: 6.083 },
    population: 132441,
    keywords: {
      primary: [
        "website laten maken zwolle",
        "webdesign zwolle",
        "webontwikkeling zwolle",
      ],
      secondary: [
        "wordpress zwolle",
        "e-commerce website zwolle",
        "seo specialist zwolle",
      ],
      longTail: [
        "professionele website laten maken zwolle",
        "responsive webdesign zwolle",
        "webshop laten bouwen zwolle",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Zwolle",
      municipality: "Zwolle",
      region: "West-Overijssel",
      dialCode: "038",
    },
  },
  {
    name: "Maastricht",
    slug: "maastricht",
    province: "Limburg",
    postalCodes: [
      "6200",
      "6201",
      "6202",
      "6203",
      "6204",
      "6205",
      "6206",
      "6207",
      "6208",
      "6209",
      "6210",
      "6211",
      "6212",
      "6213",
      "6214",
      "6215",
      "6216",
      "6217",
      "6218",
      "6219",
    ],
    coordinates: { lat: 50.8514, lng: 5.691 },
    population: 121558,
    keywords: {
      primary: [
        "website laten maken maastricht",
        "webdesign maastricht",
        "webontwikkeling maastricht",
      ],
      secondary: [
        "wordpress maastricht",
        "e-commerce website maastricht",
        "seo specialist maastricht",
      ],
      longTail: [
        "professionele website laten maken maastricht",
        "responsive webdesign maastricht",
        "webshop laten bouwen maastricht",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Maastricht",
      municipality: "Maastricht",
      region: "Zuid-Limburg",
      dialCode: "043",
    },
  },
  {
    name: "Venlo",
    slug: "venlo",
    province: "Limburg",
    postalCodes: [
      "5900",
      "5901",
      "5902",
      "5903",
      "5904",
      "5905",
      "5906",
      "5907",
      "5908",
      "5909",
      "5910",
      "5911",
      "5912",
      "5913",
      "5914",
      "5915",
      "5916",
      "5917",
      "5918",
      "5919",
    ],
    coordinates: { lat: 51.3704, lng: 6.1724 },
    population: 101797,
    keywords: {
      primary: [
        "website laten maken venlo",
        "webdesign venlo",
        "webontwikkeling venlo",
      ],
      secondary: [
        "wordpress venlo",
        "e-commerce website venlo",
        "seo specialist venlo",
      ],
      longTail: [
        "professionele website laten maken venlo",
        "responsive webdesign venlo",
        "webshop laten bouwen venlo",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Venlo",
      municipality: "Venlo",
      region: "Noord-Limburg",
      dialCode: "077",
    },
  },
  {
    name: "Deventer",
    slug: "deventer",
    province: "Overijssel",
    postalCodes: [
      "7400",
      "7401",
      "7402",
      "7403",
      "7404",
      "7405",
      "7406",
      "7407",
      "7408",
      "7409",
      "7410",
      "7411",
      "7412",
      "7413",
      "7414",
      "7415",
      "7416",
      "7417",
      "7418",
      "7419",
    ],
    coordinates: { lat: 52.2551, lng: 6.1639 },
    population: 100718,
    keywords: {
      primary: [
        "website laten maken deventer",
        "webdesign deventer",
        "webontwikkeling deventer",
      ],
      secondary: [
        "wordpress deventer",
        "e-commerce website deventer",
        "seo specialist deventer",
      ],
      longTail: [
        "professionele website laten maken deventer",
        "responsive webdesign deventer",
        "webshop laten bouwen deventer",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Deventer",
      municipality: "Deventer",
      region: "Stedendriehoek",
      dialCode: "0570",
    },
  },
  {
    name: "Delft",
    slug: "delft",
    province: "Zuid-Holland",
    postalCodes: [
      "2600",
      "2601",
      "2602",
      "2603",
      "2604",
      "2605",
      "2606",
      "2607",
      "2608",
      "2609",
      "2610",
      "2611",
      "2612",
      "2613",
      "2614",
      "2615",
      "2616",
      "2617",
      "2618",
      "2619",
    ],
    coordinates: { lat: 52.0116, lng: 4.3571 },
    population: 103659,
    keywords: {
      primary: [
        "website laten maken delft",
        "webdesign delft",
        "webontwikkeling delft",
      ],
      secondary: [
        "wordpress delft",
        "e-commerce website delft",
        "seo specialist delft",
      ],
      longTail: [
        "professionele website laten maken delft",
        "responsive webdesign delft",
        "webshop laten bouwen delft",
      ],
    },
    localInfo: {
      chamberOfCommerce: "KvK Delft",
      municipality: "Delft",
      region: "Metropoolregio Rotterdam Den Haag",
      dialCode: "015",
    },
  },
];

// Main business data for NAP consistency
export const localBusinessData: LocalBusinessData = {
  name: "ProWeb Studio",
  legalName: "ProWeb Studio B.V.",
  address: {
    streetAddress: "Hoofdstraat 123",
    addressLocality: "Amsterdam",
    postalCode: "1012 AB",
    addressRegion: "Noord-Holland",
    addressCountry: "NL",
  },
  phone: "+31686412430",
  email: "contact@prowebstudio.nl",
  url: "https://prowebstudio.nl",
  kvkNumber: "12345678",
  vatNumber: "NL123456789B01",
  businessHours: {
    monday: "09:00-17:00",
    tuesday: "09:00-17:00",
    wednesday: "09:00-17:00",
    thursday: "09:00-17:00",
    friday: "09:00-17:00",
  },
  holidays: [
    { name: "Nieuwjaarsdag", date: "2025-01-01", closed: true },
    { name: "Goede Vrijdag", date: "2025-04-18", closed: true },
    { name: "Paasmaandag", date: "2025-04-21", closed: true },
    { name: "Koningsdag", date: "2025-04-27", closed: true },
    { name: "Bevrijdingsdag", date: "2025-05-05", closed: false },
    { name: "Hemelvaart", date: "2025-05-29", closed: true },
    { name: "Pinkstermaandag", date: "2025-06-09", closed: true },
    { name: "Kerst", date: "2025-12-25", closed: true },
    { name: "Tweede Kerstdag", date: "2025-12-26", closed: true },
  ],
  serviceAreas: dutchCities.map((city) => city.name),
  categories: [
    "Website Development",
    "Web Design",
    "E-commerce Development",
    "SEO Services",
    "Digital Marketing",
    "3D Web Development",
  ],
};

// Dutch national holidays and business information
export const dutchBusinessInfo = {
  nationalHolidays: [
    { name: "Nieuwjaarsdag", date: "2025-01-01", type: "national" },
    { name: "Goede Vrijdag", date: "2025-04-18", type: "christian" },
    { name: "Paaszondag", date: "2025-04-20", type: "christian" },
    { name: "Paasmaandag", date: "2025-04-21", type: "national" },
    { name: "Koningsdag", date: "2025-04-27", type: "national" },
    { name: "Bevrijdingsdag", date: "2025-05-05", type: "liberation" },
    { name: "Hemelvaart", date: "2025-05-29", type: "christian" },
    { name: "Pinksterzondag", date: "2025-06-08", type: "christian" },
    { name: "Pinkstermaandag", date: "2025-06-09", type: "national" },
    { name: "Eerste Kerstdag", date: "2025-12-25", type: "national" },
    { name: "Tweede Kerstdag", date: "2025-12-26", type: "national" },
  ],
  businessCategories: [
    { code: "6201", name: "Ontwikkelen, produceren en uitgeven van software" },
    {
      code: "6202",
      name: "Advisering en ondersteuning op het gebied van informatietechnologie",
    },
    { code: "7311", name: "Reclamebureaus" },
    { code: "7320", name: "Markt- en opinieonderzoekbureaus" },
    { code: "7410", name: "Ontwerpen en vormgeving" },
  ],
  chamberOfCommerceRegions: [
    "Amsterdam",
    "Rotterdam",
    "Den Haag",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen",
  ],
};

// Helper functions for local SEO
export function getCityBySlug(slug: string): DutchCity | undefined {
  return dutchCities.find((city) => city.slug === slug);
}

export function getNearestCities(
  coordinates: { lat: number; lng: number },
  limit: number = 5,
): DutchCity[] {
  return dutchCities
    .map((city) => ({
      ...city,
      distance: calculateDistance(coordinates, city.coordinates),
    }))
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit);
}

function calculateDistance(
  coord1: { lat: number; lng: number },
  coord2: { lat: number; lng: number },
): number {
  const R = 6371; // Earth's radius in kilometers
  const dLat = ((coord2.lat - coord1.lat) * Math.PI) / 180;
  const dLng = ((coord2.lng - coord1.lng) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((coord1.lat * Math.PI) / 180) *
      Math.cos((coord2.lat * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

export function generateLocalKeywords(
  city: DutchCity,
  baseKeywords: string[],
): string[] {
  const localVariations = [
    ...baseKeywords.map((keyword) => `${keyword} ${city.name.toLowerCase()}`),
    ...baseKeywords.map((keyword) => `${keyword} ${city.slug}`),
    ...baseKeywords.map(
      (keyword) => `${keyword} in ${city.name.toLowerCase()}`,
    ),
    ...baseKeywords.map(
      (keyword) => `${keyword} regio ${city.localInfo.region.toLowerCase()}`,
    ),
    ...baseKeywords.map(
      (keyword) => `${keyword} ${city.province.toLowerCase()}`,
    ),
    ...(city.localInfo.dialCode
      ? baseKeywords.map((keyword) => `${keyword} ${city.localInfo.dialCode}`)
      : []),
  ];

  return Array.from(new Set(localVariations)); // Remove duplicates
}
